# Generated by Django 5.2.12 on 2026-03-17 11:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClassGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('year_group', models.PositiveSmallIntegerField(blank=True, help_text='Year group number (e.g. 3)', null=True)),
            ],
            options={
                'ordering': ['year_group', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('short_name', models.CharField(blank=True, max_length=20)),
                ('applicable_pathways', models.JSONField(blank=True, default=list, help_text='List of pathway codes, e.g. ["PREP", "FUT"]')),
                ('applicable_phases', models.JSONField(blank=True, default=list, help_text='List of phase numbers, e.g. [1, 2]')),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('upn', models.CharField(blank=True, help_text='Unique Pupil Number', max_length=13, null=True, unique=True, verbose_name='UPN')),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('pathway', models.CharField(choices=[('PREP', 'Preparations'), ('FUT', 'Futures'), ('HOR', 'Horizons')], default='PREP', max_length=4)),
                ('phase', models.PositiveSmallIntegerField(choices=[(1, 'Phase 1'), (2, 'Phase 2')], default=1)),
                ('year_group', models.PositiveSmallIntegerField(blank=True, help_text='Current year group', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('class_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='students.classgroup')),
            ],
            options={
                'ordering': ['last_name', 'first_name'],
            },
        ),
    ]
