# Generated by Django 5.2.12 on 2026-03-17 11:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('students', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssessmentFramework',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='AssessmentArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="e.g. 'Reading — Year 3'", max_length=200)),
                ('year_group', models.PositiveSmallIntegerField(blank=True, help_text='Applicable year group', null=True)),
                ('phase', models.PositiveSmallIntegerField(blank=True, help_text='Applicable phase (1 or 2)', null=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessment_areas', to='students.subject')),
                ('framework', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='areas', to='assessments.assessmentframework')),
            ],
            options={
                'ordering': ['subject', 'order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='AssessmentStatement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statement_text', models.TextField()),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order within the area')),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statements', to='assessments.assessmentarea')),
            ],
            options={
                'ordering': ['area', 'order'],
            },
        ),
        migrations.CreateModel(
            name='AssessmentRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('NYA', 'Not Yet Assessed'), ('EME', 'Emerging'), ('DEV', 'Developing'), ('SEC', 'Secure')], default='NYA', max_length=3)),
                ('assessed_date', models.DateField()),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assessed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assessments_made', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessment_records', to='students.student')),
                ('statement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='assessments.assessmentstatement')),
            ],
            options={
                'ordering': ['-assessed_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AssessmentSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_statements', models.PositiveIntegerField(default=0)),
                ('secure_count', models.PositiveIntegerField(default=0)),
                ('developing_count', models.PositiveIntegerField(default=0)),
                ('emerging_count', models.PositiveIntegerField(default=0)),
                ('not_assessed_count', models.PositiveIntegerField(default=0)),
                ('snapshot_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='assessments.assessmentarea')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='students.student')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='core.term')),
            ],
            options={
                'ordering': ['student', 'area', 'term'],
                'unique_together': {('student', 'area', 'term')},
            },
        ),
    ]
