# Generated by Django 5.2.12 on 2026-03-19 11:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0002_frameworkassignment'),
        ('students', '0002_add_explorers_pathway'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalisedFramework',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('framework', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personalisations', to='assessments.assessmentframework')),
                ('statements', models.ManyToManyField(blank=True, related_name='personalisations', to='assessments.assessmentstatement')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personalised_frameworks', to='students.student')),
            ],
            options={
                'ordering': ['student', 'framework'],
                'unique_together': {('student', 'framework')},
            },
        ),
    ]
