# Generated by Django 5.2.12 on 2026-03-26 11:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0003_personalisedframework'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="e.g. 'Foundation', 'Level 1'", max_length=200)),
                ('order', models.PositiveIntegerField(default=0)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_areas', to='assessments.assessmentarea')),
            ],
            options={
                'ordering': ['area', 'order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='assessmentstatement',
            name='sub_area',
            field=models.ForeignKey(blank=True, help_text='Optional level within the area', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='statements', to='assessments.subarea'),
        ),
    ]
