# Generated by Django 5.2.12 on 2026-03-18 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AISettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('none', 'Disabled'), ('openai', 'OpenAI'), ('azure', 'Azure OpenAI'), ('ollama', 'Ollama (local)'), ('custom', 'Custom endpoint')], default='none', max_length=10)),
                ('api_key', models.CharField(blank=True, default='', help_text='API key (stored encrypted at rest in production).', max_length=255)),
                ('endpoint_url', models.URLField(blank=True, default='', help_text='Base URL for API calls (required for Azure / Ollama / Custom).')),
                ('model_name', models.CharField(blank=True, default='', help_text='e.g. gpt-4o, gpt-3.5-turbo, llama3.', max_length=100)),
                ('enabled', models.BooleanField(default=False, help_text='Master switch — must be on for any AI features to work.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'AI settings',
                'verbose_name_plural': 'AI settings',
            },
        ),
    ]
