# Generated by Django 5.2.12 on 2026-03-18 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_aisettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aisettings',
            name='provider',
            field=models.CharField(choices=[('none', 'Disabled'), ('openai', 'OpenAI'), ('azure', 'Azure OpenAI'), ('copilot', 'Microsoft 365 Copilot'), ('gemini', 'Google Gemini'), ('ollama', 'Ollama (local)'), ('custom', 'Custom endpoint')], default='none', max_length=10),
        ),
    ]
