# Generated by Django 5.2.12 on 2026-03-20 15:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_dashboard_preference'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ArborSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_url', models.URLField(blank=True, default='', help_text='School Arbor API base URL, e.g. https://api.uk.arbor.sc/rest-v2')),
                ('app_username', models.CharField(blank=True, default='', help_text='Arbor app username (from developer portal).', max_length=255)),
                ('api_key', models.CharField(blank=True, default='', help_text='Arbor API key for your school.', max_length=500)),
                ('graphql_url', models.URLField(blank=True, default='', help_text='GraphQL endpoint, e.g. https://api.uk.arbor.sc/graphql')),
                ('enabled', models.BooleanField(default=False, help_text='Master switch — must be on for Arbor sync to work.')),
                ('last_connected', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Arbor settings',
                'verbose_name_plural': 'Arbor settings',
            },
        ),
        migrations.CreateModel(
            name='ArborMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_type', models.CharField(choices=[('assessment', 'Assessment (Subject)'), ('grade', 'Grade (Status)'), ('period', 'Progress Measurement Period (Term)'), ('grade_set', 'Grade Set')], max_length=20)),
                ('local_id', models.CharField(help_text='AssessApp identifier (e.g. subject PK, status code, term PK).', max_length=100)),
                ('local_label', models.CharField(blank=True, help_text='Human-readable label from AssessApp.', max_length=200)),
                ('arbor_id', models.CharField(blank=True, help_text='Arbor entity ID.', max_length=100)),
                ('arbor_label', models.CharField(blank=True, help_text='Human-readable label from Arbor.', max_length=200)),
                ('arbor_href', models.CharField(blank=True, help_text='Arbor REST href for this entity.', max_length=500)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['entity_type', 'local_label'],
                'unique_together': {('entity_type', 'local_id')},
            },
        ),
        migrations.CreateModel(
            name='ArborSyncLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('success', 'Success'), ('partial', 'Partial (some errors)'), ('failed', 'Failed')], default='pending', max_length=10)),
                ('records_attempted', models.PositiveIntegerField(default=0)),
                ('records_succeeded', models.PositiveIntegerField(default=0)),
                ('records_failed', models.PositiveIntegerField(default=0)),
                ('error_details', models.JSONField(blank=True, default=list, help_text='List of {student, error} dicts for failed records.')),
                ('summary', models.TextField(blank=True)),
                ('triggered_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
    ]
