# Generated by Django 5.2.12 on 2026-03-23 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_arborsettings_arbormapping_arborsynclog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='arborsettings',
            name='graphql_url',
        ),
        migrations.AlterField(
            model_name='arborsettings',
            name='base_url',
            field=models.URLField(blank=True, default='', help_text='School Arbor URL, e.g. https://west-gate.uk.arbor.sc'),
        ),
    ]
