# Generated by Django 5.2.12 on 2026-03-18 09:45

import django.db.models.deletion
import evidence.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assessments', '0001_initial'),
        ('students', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EHCPOutcome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='EHCPTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('NOT_STARTED', 'Not Started'), ('IN_PROGRESS', 'In Progress'), ('PARTIALLY_MET', 'Partially Met'), ('MET', 'Met'), ('EXCEEDED', 'Exceeded')], default='NOT_STARTED', max_length=15)),
                ('set_date', models.DateField(help_text='Date target was set')),
                ('review_date', models.DateField(blank=True, help_text='Next review date', null=True)),
                ('met_date', models.DateField(blank=True, help_text='Date target was met', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ehcp_targets_created', to=settings.AUTH_USER_MODEL)),
                ('linked_areas', models.ManyToManyField(blank=True, help_text='Assessment areas that support this target', related_name='ehcp_targets', to='assessments.assessmentarea')),
                ('outcome', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='targets', to='evidence.ehcpoutcome')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ehcp_targets', to='students.student')),
            ],
            options={
                'ordering': ['student', 'outcome', '-set_date'],
            },
        ),
        migrations.CreateModel(
            name='EHCPTargetReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('NOT_STARTED', 'Not Started'), ('IN_PROGRESS', 'In Progress'), ('PARTIALLY_MET', 'Partially Met'), ('MET', 'Met'), ('EXCEEDED', 'Exceeded')], max_length=15)),
                ('notes', models.TextField(blank=True)),
                ('review_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='evidence.ehcptarget')),
            ],
            options={
                'ordering': ['-review_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Evidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evidence_type', models.CharField(choices=[('PHOTO', 'Photo'), ('VIDEO', 'Video'), ('DOCUMENT', 'Document')], max_length=10)),
                ('title', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('file', models.FileField(upload_to=evidence.models.evidence_upload_path)),
                ('thumbnail', models.ImageField(blank=True, help_text='Auto-generated or manually set thumbnail', null=True, upload_to='evidence/thumbnails/')),
                ('is_shared_with_family', models.BooleanField(default=False, help_text='If True, visible in the parent/family portal')),
                ('shared_at', models.DateTimeField(blank=True, null=True)),
                ('captured_date', models.DateField(help_text='Date the evidence was captured/observed')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ehcp_target', models.ForeignKey(blank=True, help_text='Link to an EHCP target (optional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evidence_items', to='evidence.ehcptarget')),
                ('shared_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evidence_shared', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence_items', to='students.student')),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evidence_items', to='students.subject')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evidence_uploaded', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'evidence',
                'ordering': ['-captured_date', '-created_at'],
            },
        ),
    ]
