# Generated by Django 5.2.12 on 2026-03-18 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evidence', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='evidence',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
