# Generated by Django 5.2.12 on 2026-03-18 12:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evidence', '0002_evidence_updated_at'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evidence',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evidence_items', to='students.student'),
        ),
        migrations.CreateModel(
            name='EvidenceStudentLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ehcp_target', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evidence_student_links', to='evidence.ehcptarget')),
                ('evidence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_links', to='evidence.evidence')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence_links', to='students.student')),
            ],
            options={
                'ordering': ['student__last_name', 'student__first_name'],
                'unique_together': {('evidence', 'student')},
            },
        ),
        migrations.AddField(
            model_name='evidence',
            name='students',
            field=models.ManyToManyField(blank=True, related_name='linked_evidence', through='evidence.EvidenceStudentLink', to='students.student'),
        ),
    ]
