# Generated by Django 5.2.12 on 2026-03-18 13:09

import django.db.models.deletion
import evidence.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evidence', '0004_migrate_student_links'),
        ('students', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EHCPDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=evidence.models.ehcp_document_upload_path)),
                ('original_filename', models.CharField(max_length=255)),
                ('title', models.CharField(blank=True, max_length=300)),
                ('ocr_text', models.TextField(blank=True, default='', help_text='Raw text extracted via OCR / PDF text layer.')),
                ('edited_text', models.TextField(blank=True, default='', help_text='User-edited version of the OCR text.')),
                ('processing_status', models.CharField(choices=[('UPLOADED', 'Uploaded'), ('PROCESSING', 'Processing OCR'), ('COMPLETED', 'OCR Complete'), ('FAILED', 'OCR Failed')], default='UPLOADED', max_length=12)),
                ('page_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ehcp_documents', to='students.student')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ehcp_documents_uploaded', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
