# Generated by Django 5.2.12 on 2026-03-18 14:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evidence', '0005_add_ehcp_document'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EHCPAnnotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annotation_type', models.CharField(choices=[('highlight', 'Highlight'), ('strikethrough', 'Strikethrough'), ('textbox', 'Text Box'), ('note', 'Sticky Note')], max_length=15)),
                ('page', models.PositiveIntegerField(help_text='1-based page number')),
                ('x', models.FloatField(help_text='Left position as % of page width')),
                ('y', models.FloatField(help_text='Top position as % of page height')),
                ('width', models.FloatField(help_text='Width as % of page width')),
                ('height', models.FloatField(help_text='Height as % of page height')),
                ('color', models.CharField(default='#ffeb3b', max_length=7)),
                ('text', models.TextField(blank=True, default='', help_text='Text content for text boxes / notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annotations', to='evidence.ehcpdocument')),
            ],
            options={
                'ordering': ['page', 'y', 'x'],
            },
        ),
    ]
