# Generated by Django 5.2.12 on 2026-03-19 10:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evidence', '0007_add_small_steps_and_mapp'),
        ('students', '0002_add_explorers_pathway'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InterventionProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('SALT', 'Speech & Language'), ('OT', 'Occupational Therapy'), ('PHYSIO', 'Physiotherapy'), ('SOCIAL', 'Social Skills'), ('ELSA', 'Emotional Literacy'), ('READING', 'Reading'), ('MATHS', 'Maths'), ('SENSORY', 'Sensory'), ('BEHAVIOUR', 'Behaviour'), ('OTHER', 'Other')], default='OTHER', max_length=12)),
                ('description', models.TextField(blank=True)),
                ('default_frequency', models.CharField(blank=True, help_text="e.g. '3x per week', 'Daily'", max_length=50)),
                ('default_duration_mins', models.PositiveIntegerField(blank=True, help_text='Default session length in minutes', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='MAPPConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="e.g. 'Standard MAPP', 'MAPP with 5 dimensions'", max_length=100)),
                ('scale_min', models.PositiveSmallIntegerField(default=1, help_text='Lowest CSD scale value')),
                ('scale_max', models.PositiveSmallIntegerField(default=10, help_text='Highest CSD scale value')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'MAPP configuration',
                'ordering': ['-is_active', 'name'],
            },
        ),
        migrations.AlterField(
            model_name='mappdimensionscore',
            name='baseline_csd',
            field=models.PositiveSmallIntegerField(help_text='Baseline position on CSD scale'),
        ),
        migrations.AlterField(
            model_name='mappdimensionscore',
            name='current_score',
            field=models.PositiveSmallIntegerField(default=0, help_text='Steps progressed from baseline'),
        ),
        migrations.AlterField(
            model_name='mappdimensionscore',
            name='dimension',
            field=models.CharField(choices=[('IND', 'Independence'), ('FLU', 'Fluency'), ('MAI', 'Maintenance'), ('GEN', 'Generalisation')], max_length=5),
        ),
        migrations.CreateModel(
            name='InterventionEnrolment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('COMPLETED', 'Completed'), ('PAUSED', 'Paused'), ('WITHDRAWN', 'Withdrawn')], default='ACTIVE', max_length=12)),
                ('frequency', models.CharField(blank=True, help_text="e.g. '2x per week'", max_length=50)),
                ('duration_mins', models.PositiveIntegerField(blank=True, help_text='Session length in minutes', null=True)),
                ('goals', models.TextField(blank=True, help_text='What this intervention aims to achieve')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('delivered_by', models.ForeignKey(blank=True, help_text='Staff member delivering this intervention', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interventions_delivering', to=settings.AUTH_USER_MODEL)),
                ('ehcp_target', models.ForeignKey(blank=True, help_text='Link to an EHCP target (optional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interventions', to='evidence.ehcptarget')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interventions', to='students.student')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrolments', to='evidence.interventionprogram')),
            ],
            options={
                'verbose_name': 'intervention enrolment',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='InterventionReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_date', models.DateField()),
                ('impact', models.CharField(choices=[('SIGNIFICANT', 'Significant Progress'), ('GOOD', 'Good Progress'), ('SOME', 'Some Progress'), ('LIMITED', 'Limited Progress'), ('NONE', 'No Progress'), ('REGRESSION', 'Regression')], max_length=15)),
                ('progress_notes', models.TextField(help_text='Evidence of progress / impact')),
                ('next_steps', models.TextField(blank=True, help_text='Recommended next actions')),
                ('continue_intervention', models.BooleanField(default=True, help_text='Should this intervention continue?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('enrolment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='evidence.interventionenrolment')),
                ('reviewed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-review_date'],
            },
        ),
        migrations.CreateModel(
            name='InterventionSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_date', models.DateField()),
                ('attended', models.BooleanField(default=True)),
                ('duration_mins', models.PositiveIntegerField(blank=True, help_text='Actual session length (if different from planned)', null=True)),
                ('notes', models.TextField(blank=True, help_text='Brief session notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('enrolment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='evidence.interventionenrolment')),
                ('recorded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-session_date'],
            },
        ),
        migrations.CreateModel(
            name='MAPPDimensionConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Short code, e.g. IND, FLU', max_length=5)),
                ('name', models.CharField(help_text='Full name, e.g. Independence', max_length=100)),
                ('order', models.PositiveIntegerField(default=0)),
                ('config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dimension_configs', to='evidence.mappconfig')),
            ],
            options={
                'verbose_name': 'MAPP dimension',
                'ordering': ['config', 'order'],
                'unique_together': {('config', 'code')},
            },
        ),
        migrations.AddField(
            model_name='mappdimensionscore',
            name='dimension_config',
            field=models.ForeignKey(blank=True, help_text='Links to the config dimension (if using configurable MAPP)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='evidence.mappdimensionconfig'),
        ),
    ]
